### ISSUE TITLE
Workflow error 

### ISSUE THREAD

**Issue by carolinehey** [epi2me-labs/wf-human-variation#107]
### Operating System

Windows 10

### Workflow Version

v1.8.2

### Workflow Execution

Command line

### CLI command run

nextflow run epi2me-labs/wf-human-variation -r v1.8.2 -w /data/wf_hum_C -profile standard --phase-mod --snp --sv --cnv --bin_size 15 -c /longread/resources/increase_memory.config --bam_min_coverage 1 --bam Kira_merged_ubam.bam --ref /longread/resources/reference_genomes/GRCh38_Hg38/GRCh38_decoy_no_alt.fasta --sample_name Kira_hg38 --out_dir /longread/Annette/Kira_blod/wf-human-variation-hg38

### Workflow Execution - CLI Execution Profile

None

### What happened?

I'm not sure why I get this error.

### Relevant log output

```shell
Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 1.

The full error message was:

Error executing process > 'configure_jbrowse (1)'

Caused by:
  Process `configure_jbrowse (1)` terminated with an error exit status (1)

Command executed:

  workflow-glue configure_jbrowse         --reference GRCh38_decoy_no_alt.fasta "/longread/Annette/Kira_blod/wf-human-variation-hg38/GRCh38_decoy_no_alt.fasta" "/longread/Annette/Kira_blod/wf-human-variation-hg38/GRCh38_decoy_no_alt.fasta.fai"         --alignment /longread/Annette/Kira_blod/wf-human-variation-hg38/Kira_hg38.bam /longread/Annette/Kira_blod/wf-human-variation-hg38/Kira_hg38.bam.bai         --variant snp /longread/Annette/Kira_blod/wf-human-variation-hg38/Kira_hg38.wf_snp.vcf.gz /longread/Annette/Kira_blod/wf-human-variation-hg38/Kira_hg38.wf_snp.vcf.gz.tbi         --variant sv /longread/Annette/Kira_blod/wf-human-variation-hg38/Kira_hg38.wf_sv.vcf.gz /longread/Annette/Kira_blod/wf-human-variation-hg38/Kira_hg38.wf_sv.vcf.gz.tbi > jbrowse.json

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/root/.nextflow/assets/epi2me-labs/wf-human-variation/bin/workflow-glue", line 7, in 
      cli()
    File "/root/.nextflow/assets/epi2me-labs/wf-human-variation/bin/workflow_glue/__init__.py", line 51, in cli
      f'{_package_name}.{comp}' for comp in get_components()]
    File "/root/.nextflow/assets/epi2me-labs/wf-human-variation/bin/workflow_glue/__init__.py", line 22, in get_components
      mod = importlib.import_module(f"{_package_name}.{name}")
    File "/home/epi2melabs/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "", line 1014, in _gcd_import
    File "", line 991, in _find_and_load
    File "", line 975, in _find_and_load_unlocked
    File "", line 671, in _load_unlocked
    File "", line 843, in exec_module
    File "", line 219, in _call_with_frames_removed
    File "/root/.nextflow/assets/epi2me-labs/wf-human-variation/bin/workflow_glue/report_qc.py", line 4, in 
      from aplanat import annot, hist, report
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/aplanat/__init__.py", line 12, in 
      from bokeh.plotting import Figure
  ImportError: cannot import name 'Figure' from 'bokeh.plotting' (/home/epi2melabs/conda/lib/python3.8/site-packages/bokeh/plotting/__init__.py)

Work dir:
  /data/wf_hum_C/e4/d13d51c839f01010dca7a8929034ac

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

**Comment by SamStudio8** [comment]
@carolinehey This is a little strange as this appears to be a known issue that was fixed many versions ago. It would appear from the line numbering in your error that you may have an older version of the "workflow-glue" script used to bundle some of our utilities in a pseudo package. It's possible that `nextflow pull` has been unable to update this file, or for some reason you may have some older Python object files occluding the newer script.

Can you remove your installed version of the workflow with `nextflow drop epi2me-labs/wf-human-variation` and pull a fresh copy with `nextflow pull epi2me-labs/wf-human-variation`?

**Comment by SamStudio8** [comment]
Closing due to lack of response, please get in touch if you're still running in to trouble!
