### ISSUE TITLE
[Bug]: sv:runReport:report` terminated with an error exit status

### ISSUE THREAD

**Issue by neurogenetics1** [epi2me-labs/wf-human-variation#19]
### What happened?

I got the following error. Any help is appreciated.

Error executing process > 'sv:runReport:report'

Caused by:
  Process `sv:runReport:report` terminated with an error exit status (1)

Command executed:

  report_sv.py         AZ140021.wf-human-sv-report.html         --vcf AZ140021.wf_sv.vcf.gz                  --read_depth AZ140021.mosdepth.global.dist.txt         --params params.json         --params-hidden 'help,schema_ignore_params,show_hidden_params,validate_params,monochrome_logs,aws_queue,aws_image_prefix,wfversion,wf,process_label,min_sv_length,max_sv_length,min_read_support,min_read_support_limit'         --versions versions.txt         --revision master         --commit 568e8f6875857895f82bc1320bdfd82425d2622d

Command exit status:
  1

Command output:
  (empty)

Command error:
  /home/epi2melabs/conda/lib/python3.8/site-packages/icon_font_to_png/icon_font.py:39: DeprecationWarning: invalid escape sequence \.
    is_icon = re.compile("\.(.*):before,?")
  /home/epi2melabs/conda/lib/python3.8/site-packages/tinycss/token_data.py:216: DeprecationWarning: invalid escape sequence \`
    """A single atomic token.
  /home/epi2melabs/conda/lib/python3.8/site-packages/si_prefix/__init__.py:44: DeprecationWarning: invalid escape sequence \s
    u'(?P<si_unit>[%s])?\s*' % SI_PREFIX_UNITS)
  /home/epi2melabs/conda/lib/python3.8/site-packages/si_prefix/__init__.py:249: DeprecationWarning: invalid escape sequence \s
    u'(?P<si_unit>[%s])?\s*$' % SI_PREFIX_UNITS)
  Traceback (most recent call last):
    File "/home/akcimenf2/.nextflow/22.10.2/assets/epi2me-labs/wf-human-variation/bin/report_sv.py", line 324, in <module>
      main()
    File "/home/akcimenf2/.nextflow/22.10.2/assets/epi2me-labs/wf-human-variation/bin/report_sv.py", line 201, in main
      vcf_df = read_vcf(sample_vcf)
    File "/home/akcimenf2/.nextflow/22.10.2/assets/epi2me-labs/wf-human-variation/bin/report_sv.py", line 24, in read_vcf
      df = pd.read_csv(fname, comment='#', header=None, delimiter='\t')
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
      return func(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
      return func(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
      return _read(filepath_or_buffer, kwds)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
      parser = TextFileReader(filepath_or_buffer, **kwds)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
      self._engine = self._make_engine(f, self.engine)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1753, in _make_engine
      return mapping[engine](f, **self.options)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 79, in __init__
      self._reader = parsers.TextReader(src, **kwds)
    File "pandas/_libs/parsers.pyx", line 554, in pandas._libs.parsers.TextReader.__cinit__
  pandas.errors.EmptyDataError: No columns to parse from file

I used following options:

Core Nextflow options
  revision                  : master
  runName                   : agitated_visvesvaraya
  containerEngine           : singularity
  container                 : ontresearch/wf-human-variation:shac4db03c19b6ff1277a24ec28a19e564d628d478f
  launchDir                 : /vf/users/nanopore/AZ140021
  workDir                   : /vf/users/nanopore/AZ140021/work
  projectDir                : /home/uname/.nextflow/22.10.2/assets/epi2me-labs/wf-human-variation
  profile                   : biowulf
  configFiles               : /home/uname/.nextflow/22.10.2/assets/epi2me-labs/wf-human-variation/nextflow.config, /vf/users/nanopore/AZ140021/nextflow.config

Workflow Options
  sv                        : true
  snp                       : true
  methyl                    : true

Input Options
  bam                       : /data/nanopore/AZ140021/20220307_1824_2D_PAI72310_c23d05c2/output2023/SAMPLE.pass.cram
  ref                       : /data/nanopore/AZ140021/GRCh38.fa
  old_ref                   : /data/nanopore/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa
  basecaller_cfg            : dna_r10.4.1_e8.2_400bps_hac@v3.5.2

Structural variant calling options
  sv_types                  : DEL,INS,INV,CNV,DUP

Small variant calling options
  include_all_ctgs          : true
  GVCF                      : true
  clair3_model_path         : /usr/local/apps/Clair3/v0.1-r11.1/trainedModels/ont

Basecalling options
  remora_cfg                : dna_r10.4.1_e8.2_400bps_hac@v3.5.2_5mCG@v2
  basecaller_basemod_threads: 40

Output Options
  sample_name               : AZ140021
  out_dir                   : /data/nanopore/AZ140021/20220307_1824_2D_PAI72310_c23d05c2/output2023

Multiprocessing Options
  threads                   : 40
  ubam_map_threads          : 8
  ubam_sort_threads         : 3
  ubam_bam2fq_threads       : 1

Other parameters
  process_label             : wfdefault

### Operating System

ubuntu 18.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Singularity

### Workflow Version

wf-human-variation v1.1.0-g568e8f6

### Relevant log output

```shell
Command output:
  (empty)

Command error:
  /home/epi2melabs/conda/lib/python3.8/site-packages/icon_font_to_png/icon_font.py:39: DeprecationWarning: invalid escape sequence \.
    is_icon = re.compile("\.(.*):before,?")
  /home/epi2melabs/conda/lib/python3.8/site-packages/tinycss/token_data.py:216: DeprecationWarning: invalid escape sequence \`
    """A single atomic token.
  /home/epi2melabs/conda/lib/python3.8/site-packages/si_prefix/__init__.py:44: DeprecationWarning: invalid escape sequence \s
    u'(?P<si_unit>[%s])?\s*' % SI_PREFIX_UNITS)
  /home/epi2melabs/conda/lib/python3.8/site-packages/si_prefix/__init__.py:249: DeprecationWarning: invalid escape sequence \s
    u'(?P<si_unit>[%s])?\s*$' % SI_PREFIX_UNITS)
  Traceback (most recent call last):
    File "/home/akcimenf2/.nextflow/22.10.2/assets/epi2me-labs/wf-human-variation/bin/report_sv.py", line 324, in <module>
      main()
    File "/home/akcimenf2/.nextflow/22.10.2/assets/epi2me-labs/wf-human-variation/bin/report_sv.py", line 201, in main
      vcf_df = read_vcf(sample_vcf)
    File "/home/akcimenf2/.nextflow/22.10.2/assets/epi2me-labs/wf-human-variation/bin/report_sv.py", line 24, in read_vcf
      df = pd.read_csv(fname, comment='#', header=None, delimiter='\t')
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
      return func(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
      return func(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
      return _read(filepath_or_buffer, kwds)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
      parser = TextFileReader(filepath_or_buffer, **kwds)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
      self._engine = self._make_engine(f, self.engine)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1753, in _make_engine
      return mapping[engine](f, **self.options)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 79, in __init__
      self._reader = parsers.TextReader(src, **kwds)
    File "pandas/_libs/parsers.pyx", line 554, in pandas._libs.parsers.TextReader.__cinit__
  pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by SamStudio8** [comment]
Hi @neurogenetics1, thanks for this report. The SV report step has failed here because there are no SVs in the VCF to report. The workflow should handle this more elegantly than exploding so I have raised a ticket internally to fix this.

**Comment by SamStudio8** [comment]
This has been fixed in a recent release of the workflow, thanks for reporting.
