### ISSUE TITLE
Error running help command

### ISSUE THREAD

**Issue by keenhl** [epi2me-labs/wf-human-variation#41]
### What happened?

I tried to run the help command and I get an error.

nextflow run epi2me-labs/wf-human-variation --help

Thank you for your help.

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

v1.5.2

### Relevant log output

```shell
May-22 16:10:07.325 [main] DEBUG nextflow.cli.Launcher - $> nextflow run epi2me-labs/wf-human-variation --help
May-22 16:10:07.960 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 21.10.6
May-22 16:10:13.034 [main] DEBUG nextflow.scm.AssetManager - Git config: /Users/keenhl/.nextflow/assets/epi2me-labs/wf-human-variation/.git/config; branch: master; remote: origin; url: https://github.com/epi2me-labs/wf-human-va
riation.git
May-22 16:10:13.052 [main] DEBUG nextflow.scm.AssetManager - Git config: /Users/keenhl/.nextflow/assets/epi2me-labs/wf-human-variation/.git/config; branch: master; remote: origin; url: https://github.com/epi2me-labs/wf-human-va
riation.git
May-22 16:10:13.673 [main] INFO  nextflow.cli.CmdRun - Launching `epi2me-labs/wf-human-variation` [crazy_lichterman] - revision: ac6fdb9bf5 [master]
May-22 16:10:15.149 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /Users/keenhl/.nextflow/assets/epi2me-labs/wf-human-variation/nextflow.config
May-22 16:10:15.150 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /Shared/Bioinformatics/data/keenhl/wong/nextflow/24_repeat_23_no_condition/nextflow.config
May-22 16:10:15.151 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /Users/keenhl/.nextflow/assets/epi2me-labs/wf-human-variation/nextflow.config
May-22 16:10:15.151 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /Shared/Bioinformatics/data/keenhl/wong/nextflow/24_repeat_23_no_condition/nextflow.config
May-22 16:10:15.227 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
May-22 16:10:16.225 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
May-22 16:10:16.633 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; plugins-dir=/Users/keenhl/.nextflow/plugins
May-22 16:10:16.637 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
May-22 16:10:16.657 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
May-22 16:10:16.659 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
May-22 16:10:16.664 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
May-22 16:10:16.735 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
May-22 16:10:16.916 [main] DEBUG nextflow.Session - Session uuid: 6aa198ce-7a39-4c33-b7a6-89f346c83723
May-22 16:10:16.916 [main] DEBUG nextflow.Session - Run name: crazy_lichterman
May-22 16:10:16.916 [main] DEBUG nextflow.Session - Executor pool size: 2
May-22 16:10:16.944 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 21.10.6 build 5660
  Created: 21-12-2021 16:55 UTC (10:55 CDT)
  System: Linux 3.10.0-1160.83.1.el7.x86_64
  Runtime: Groovy 3.0.9 on OpenJDK 64-Bit Server VM 1.8.0_362-b08
  Encoding: UTF-8 (UTF-8)
  Process: 118246@argon-itf-login-4.hpc [172.29.6.106]
  CPUs: 1 - Mem: 8 GB (96.5 MB) - Swap: 4 GB (3.9 GB)
May-22 16:10:17.474 [main] DEBUG nextflow.Session - Work-dir: /Shared/Bioinformatics/data/keenhl/wong/nextflow/24_repeat_23_no_condition/work [nfs]
May-22 16:10:17.555 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
May-22 16:10:17.633 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
May-22 16:10:18.032 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 2; maxThreads: 1000
May-22 16:10:18.452 [main] DEBUG nextflow.Session - Session start invoked
May-22 16:10:18.475 [main] DEBUG nextflow.trace.TraceFileObserver - Flow starting -- trace file: /Shared/Bioinformatics/data/keenhl/wong/nextflow/24_repeat_23_no_condition/pipeline_info/execution_trace.txt
May-22 16:10:18.546 [main] DEBUG nextflow.Session - Using default localLib path: /Users/keenhl/.nextflow/assets/epi2me-labs/wf-human-variation/lib
May-22 16:10:18.559 [main] DEBUG nextflow.Session - Adding to the classpath library: /Users/keenhl/.nextflow/assets/epi2me-labs/wf-human-variation/lib
May-22 16:10:18.559 [main] DEBUG nextflow.Session - Adding to the classpath library: /Users/keenhl/.nextflow/assets/epi2me-labs/wf-human-variation/lib/nfcore_external_java_deps.jar
May-22 16:10:26.748 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
May-22 16:10:41.138 [main] DEBUG nextflow.Session - Session aborted -- Cause: 1
May-22 16:10:41.227 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.codehaus.groovy.runtime.dgmimpl.arrays.ObjectArrayGetAtMetaMethod.invoke(ObjectArrayGetAtMetaMethod.java:41)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.invoke(PojoMetaMethodSite.java:51)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at NfcoreTemplate.logo(NfcoreTemplate.groovy:325)
	at NfcoreTemplate$logo.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
	at WorkflowMain.help(WorkflowMain.groovy:19)
	at WorkflowMain$help$0.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:249)
	at WorkflowMain.initialise(WorkflowMain.groovy:42)
	at WorkflowMain$initialise.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157)
	at Script_d91d5723.runScript(Script_d91d5723:44)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:169)
	at nextflow.script.BaseScript.run(BaseScript.groovy:200)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:308)
	at nextflow.cli.Launcher.run(Launcher.groovy:480)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)
```

**Comment by keenhl** [comment]
Solved by updating java to the following

openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)
