### ISSUE TITLE
[Bug]: Missing output file(s) `candidate_bed/chrUn_KI270381v1.*` expected by process `clair3:create_candidates (34)`

### ISSUE THREAD

**Issue by felixm3** [epi2me-labs/wf-human-variation#6]
### What happened?

Trying to call variants on a WGS BAM file generated from `minimap2` using this command:

```
nextflow run epi2me-labs/wf-human-variation \
    -w output/workspace \
    -profile conda \
    --snp --sv \
    --bam $1 \
    --bed $wgs_hg38_bed \
    --ref $hg38_ref \
    --model /home/fmbuga/.conda/envs/clair3a/bin/models/r941_prom_sup_g5014 \
    --out_dir output/$start \
    --threads 8 \
    --include_all_ctgs y


```

After running for ~11 hours, the Nextflow report says:

```

Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 0.

The full error message was:

Error executing process > 'clair3:create_candidates (34)'

Caused by:
  Missing output file(s) `candidate_bed/chrUn_KI270381v1.*` expected by process `clair3:create_candidates (34)`

Command executed:

  pypy $(which clair3.py) SelectCandidates             --pileup_vcf_fn pileup.vcf.gz             --split_folder candidate_bed             --ref_fn hg38.fa             --var_pct_full 0.7             --ref_pct_full 0.1             --platform ont             --ctgName chrUn_KI270381v1

Command exit status:
  0

Command output:
  [93m[WARNING] Cannot find any low-quality 0/0, 0/1 or 1/1 variant in pileup output in contig chrUn_KI270381v1[0m

Command error:
  [INFO] Low quality reference calls to be processed in chrUn_KI270381v1: 0
  [INFO] Low quality variants to be processed in chrUn_KI270381v1: 0


```

Here's my BED file
[hg38.wgs.50k.bed.txt](https://github.com/epi2me-labs/wf-human-variation/files/9532457/hg38.wgs.50k.bed.txt)

### Operating System

macOS

### Workflow Execution

Command line

### Workflow Execution - Execution Profile

Conda

### Workflow Version

No idea. How do I get this information?

### Relevant log output

```shell
Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 0.

The full error message was:

Error executing process > 'clair3:create_candidates (34)'

Caused by:
  Missing output file(s) `candidate_bed/chrUn_KI270381v1.*` expected by process `clair3:create_candidates (34)`

Command executed:

  pypy $(which clair3.py) SelectCandidates             --pileup_vcf_fn pileup.vcf.gz             --split_folder candidate_bed             --ref_fn hg38.fa             --var_pct_full 0.7             --ref_pct_full 0.1             --platform ont             --ctgName chrUn_KI270381v1

Command exit status:
  0

Command output:
  [93m[WARNING] Cannot find any low-quality 0/0, 0/1 or 1/1 variant in pileup output in contig chrUn_KI270381v1[0m

Command error:
  [INFO] Low quality reference calls to be processed in chrUn_KI270381v1: 0
  [INFO] Low quality variants to be processed in chrUn_KI270381v1: 0
```

**Comment by felixm3** [comment]
Any luck with this @SamStudio8?

**Comment by SamStudio8** [comment]
Thanks for your patience @felixm3, I was concerned that my fix to set the output BEDs from this step as optional might have had some impact in the workflow downstream but we've convinced ourselves this should be OK and my proposed patch has been released today in v0.3.0. Please let me know if this works (or not!).

**Comment by felixm3** [comment]
Now I keep getting a fatal error after about a minute and a half of running.

Looks like it's something about mamba locking?

Also, the Nextflow output is formatting strangely now for some reason.

```
N E X T F L O W ~ version 21.10.6 Launching `epi2me-labs/wf-human-variation` [sleepy_ekeblad] - revision: 627b26b3e7 [master] Core Nextflow options revision : master runName : sleepy_ekeblad container : ontresearch/wf-human-variation:shab3358c08b332f9d113caa258b6daea245184bc00 launchDir : /home/fmbuga/nanopore/nf workDir : /home/fmbuga/nanopore/nf/output/workspace projectDir : /home/fmbuga/.nextflow/assets/epi2me-labs/wf-human-variation userName : fmbuga profile : conda configFiles : /home/fmbuga/.nextflow/assets/epi2me-labs/wf-human-variation/nextflow.config Basic Input/Output Options bam : /home/fmbuga/nanopore/rogstrix/2022_07_22_08_21_32/bams/all.bam ref : /home/fmbuga/tools/hg38/hg38.fa bed : /home/fmbuga/tools/bedtools/hg38.wgs.50k.bed model : /home/fmbuga/.conda/envs/clair3a/bin/models/r941_prom_sup_g5014 out_dir : output/1665289962 threads : 8 ubam_sort_threads : 3 ubam_bam2fq_threads: 1 wf-human-sv options sv : true wf-human-snp options snp : true include_all_ctgs : true Other parameters process_label : wfdefault !! 

Only displaying parameters that differ from the pipeline defaults !! ------------------------------------------------------ 

If you use epi2me-labs/wf-human-variation for your analysis please cite: 220710_P_scratch.ipynb demo2.filtered.bam demo900.filtered.bam demo9.filtered.bam demo_data demo_data.tar.gz demo.filtered.bam epi2me-labs my_artic_output my_config.cfg output tutorial.nf wf-artic work The nf-core framework https://doi.org/10.1038/s41587-020-0439-x 

[- ] process > check_for_alignment - [- ] process > minimap2_ubam - [- ] process > cram_cache - [- ] process > mosdepth - [- ] process > mapula - [- ] process > snp:make_chunks - [- ] process > snp:pileup_variants - [- ] process > snp:aggregate_pileup_variants - [- ] process > snp:select_het_snps - [- ] process > snp:phase_contig - [- ] process > snp:get_qual_filter - [- ] process > snp:create_candidates - [- ] process > snp:evaluate_candidates - [- ] process > snp:aggregate_full_align_va... - [- ] process > check_for_alignment - [- ] process > minimap2_ubam - [- ] process > cram_cache - [- ] process > mosdepth - [- ] process > mapula - [- ] process > snp:make_chunks - [- ] process > snp:pileup_variants - [- ] process > snp:aggregate_pileup_variants - [- ] process > snp:select_het_snps - [- ] process > snp:phase_contig - [- ] process > snp:get_qual_filter - [- ] process > snp:create_candidates - [- ] process > snp:evaluate_candidates - [- ] process > snp:aggregate_full_align_va... - [- ] process > snp:merge_pileup_and_full_vars - [- ] process > snp:aggregate_all_variants - [- ] process > snp:readStats - [- ] process > snp:getVersions - [- ] process > snp:getParams - [- ] process > snp:vcfStats - [- ] process > snp:makeReport - [- ] process > output_snp - [- ] process > sv:variantCall:filterBam - [- ] process > sv:variantCall:sniffles2 - [- ] process > sv:variantCall:filterCalls - [- ] process > sv:variantCall:sortVCF - [- ] process > sv:variantCall:indexVCF - [- ] process > sv:runReport:getVersions - [- ] process > sv:runReport:getParams - [- ] process > sv:runReport:report - [- ] process > output_sv - [- ] process > publish_artifact - [- ] process > check_for_alignment - [- ] process > minimap2_ubam - [- ] process > cram_cache - [- ] process > mosdepth - [- ] process > mapula - [- ] process > snp:make_chunks - [- ] process > snp:pileup_variants - [- ] process > snp:aggregate_pileup_variants - [- ] process > snp:select_het_snps - [- ] process > snp:phase_contig - [- ] process > snp:get_qual_filter - [- ] process > snp:create_candidates - [- ] process > snp:evaluate_candidates - [- ] process > snp:aggregate_full_align_va... - [- ] process > snp:merge_pileup_and_full_vars - [- ] process > snp:aggregate_all_variants - [- ] process > snp:readStats - [- ] process > snp:getVersions - [- ] process > snp:getParams - [- ] process > snp:vcfStats - [- ] process > snp:makeReport - [- ] process > output_snp - [- ] process > sv:variantCall:filterBam - [- ] process > sv:variantCall:sniffles2 - [- ] process > sv:variantCall:filterCalls - [- ] process > sv:variantCall:sortVCF - [- ] process > sv:variantCall:indexVCF - [- ] process > sv:runReport:getVersions - [- ] process > sv:runReport:getParams - [- ] process > sv:runReport:report - [- ] 
process > output_sv - [- ] 

process > publish_artifact - Creating env using mamba: /home/fmbuga/.nextflow/assets/epi2me-labs/wf-human-variation/environment_snp.yaml [cache /home/fmbuga/nanopore/nf/output/workspace/conda/epi2melabs-nf-human-snp-93b648cc4eff10f4de7cfc86eaa79198] 
Creating env using mamba: /home/fmbuga/.nextflow/assets/epi2me-labs/wf-human-variation/environment_sv.yaml [cache /home/fmbuga/nanopore/nf/output/workspace/conda/epi2melabs-wf-human-sv-92d947f1f2139701fe2b7c5b2adb0786] [- ] 

process > check_for_alignment - [- ] process > minimap2_ubam - [- ] process > cram_cache - [- ] process > mosdepth - [- ] process > mapula - [- ] process > snp:make_chunks - [- ] process > snp:pileup_variants - [- ] process > snp:aggregate_pileup_variants - [- ] process > snp:select_het_snps - [- ] process > snp:phase_contig - [- ] process > snp:get_qual_filter - [- ] process > snp:create_candidates - [- ] process > snp:evaluate_candidates - [- ] process > snp:aggregate_full_align_va... - [- ] process > snp:merge_pileup_and_full_vars - [- ] process > snp:aggregate_all_variants - [- ] process > snp:readStats - [- ] process > snp:getVersions - [- ] process > snp:getParams - [- ] process > snp:vcfStats - [- ] process > snp:makeReport - [- ] process > output_snp - [- ] process > sv:variantCall:filterBam - [- ] process > sv:variantCall:sniffles2 - [- ] process > sv:variantCall:filterCalls - [- ] process > sv:variantCall:sortVCF - [- ] process > sv:variantCall:indexVCF - [- ] process > sv:runReport:getVersions - [- ] process > sv:runReport:getParams - [- ] process > sv:runReport:report - [- ] process > output_sv - [- ] 

process > publish_artifact - Creating env using mamba: /home/fmbuga/.nextflow/assets/epi2me-labs/wf-human-variation/environment_snp.yaml [cache /home/fmbuga/nanopore/nf/output/workspace/conda/epi2melabs-nf-human-snp-93b648cc4eff10f4de7cfc86eaa79198] 
Creating env using mamba: /home/fmbuga/.nextflow/assets/epi2me-labs/wf-human-variation/environment_sv.yaml [cache /home/fmbuga/nanopore/nf/output/workspace/conda/epi2melabs-wf-human-sv-92d947f1f2139701fe2b7c5b2adb0786] 
Creating env using mamba: /home/fmbuga/.nextflow/assets/epi2me-labs/wf-human-variation/environment.yaml [cache /home/fmbuga/nanopore/nf/output/workspace/conda/epi2melabs-nf-human-variation-common-2e4f99e4a539bbd41a8f6c9addb2f248] [- ] 

process > check_for_alignment - [- ] process > minimap2_ubam - [- ] process > cram_cache - [- ] process > mosdepth - [- ] process > mapula - [- ] process > snp:make_chunks - [- ] process > snp:pileup_variants - [- ] process > snp:aggregate_pileup_variants - [- ] process > snp:select_het_snps - [- ] process > snp:phase_contig - [- ] process > snp:get_qual_filter - [- ] process > snp:create_candidates - [- ] process > snp:evaluate_candidates - [- ] process > snp:aggregate_full_align_va... - [- ] process > snp:merge_pileup_and_full_vars - [- ] process > snp:aggregate_all_variants - [- ] process > snp:readStats - [- ] process > snp:getVersions - [- ] process > snp:getParams - [- ] process > snp:vcfStats - [- ] process > snp:makeReport - [- ] process > output_snp - [- ] process > sv:variantCall:filterBam - [- ] process > sv:variantCall:sniffles2 - [- ] process > sv:variantCall:filterCalls - [- ] process > sv:variantCall:sortVCF - [- ] process > sv:variantCall:indexVCF - [- ] process > sv:runReport:getVersions - [- ] process > sv:runReport:getParams - [- ] process > sv:runReport:report - [- ] process > output_sv - [- ] process > publish_artifact - 

Error executing process > 'sv:runReport:getParams' Caused by: Failed to create Conda environment command: mamba env create --prefix /home/fmbuga/nanopore/nf/output/workspace/conda/epi2melabs-wf-human-sv-92d947f1f2139701fe2b7c5b2adb0786 --file /home/fmbuga/.nextflow/assets/epi2me-labs/wf-human-variation/environment_sv.yaml status : 1 message: warning libmamba Cannot lock '/home/fmbuga/.conda/envs/clair3a/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/envs/clair3a/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/envs/clair3a/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/envs/clair3a/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/envs/clair3a/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/envs/clair3a/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/envs/clair3a/pkgs/cache/497deca9.json' Waiting for other mamba process to finish error libmamba 

Error opening for reading "/home/fmbuga/.conda/envs/clair3a/pkgs/zlib-1.2.12-h166bdaf_4/info/index.json": No such file or directory 

error libmamba Error when extracting package: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal # 

>>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<< Traceback (most recent call last): File "/home/fmbuga/.conda/envs/clair3a/lib/python3.9/site-packages/conda/exceptions.py", line 1125, in __call__ return func(*args, **kwargs) File "/home/fmbuga/.conda/envs/clair3a/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call exit_code = getattr(module, func_name)(args, parser) File "/home/fmbuga/.conda/envs/clair3a/lib/python3.9/site-packages/conda/notices/core.py", line 72, in wrapper return_value = func(*args, **kwargs) File "/home/fmbuga/.conda/envs/clair3a/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 156, in execute result[installer_type] = installer.install(prefix, pkg_specs, args, env) File "/home/fmbuga/.conda/envs/clair3a/lib/python3.9/site-packages/mamba/mamba_env.py", line 153, in mamba_install transaction.fetch_extract_packages() RuntimeError: Found incorrect download: zlib. Aborting `$ /home/fmbuga/.conda/envs/clair3a/bin/mamba create --prefix /home/fmbuga/nanopore/nf/output/workspace/conda/epi2melabs-wf-human-sv-92d947f1f2139701fe2b7c5b2adb0786 --file /home/fmbuga/.nextflow/assets/epi2me-labs/wf-human-variation/environment_sv.yaml` environment variables: CIO_TEST=<not set> CONDA_AUTO_UPDATE_CONDA=false CONDA_DEFAULT_ENV=clair3a CONDA_EXE=/home/fmbuga/.conda/envs/clair3a/bin/conda CONDA_PREFIX=/home/fmbuga/.conda/envs/clair3a CONDA_PREFIX_1=/opt/intel/intelpython3 CONDA_PREFIX_2=/home/fmbuga/.conda/envs/gatk4 CONDA_PROMPT_MODIFIER=(clair3a) CONDA_PYTHON_EXE=/home/fmbuga/.conda/envs/clair3a/bin/python CONDA_ROOT=/home/fmbuga/.conda/envs/clair3a CONDA_SHLVL=3 CURL_CA_BUNDLE=<not set> GDL_PATH=+/usr/share/gnudatalanguage JAVA_LD_LIBRARY_PATH=/home/fmbuga/.conda/envs/clair3a/jre/lib/amd64/server MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles:/act/modulefiles PATH=/home/fmbuga/.conda/envs/clair3a/bin:/opt/intel/intelpython3/condabin: /usr/lib64/qt-3.3/bin:/home/fmbuga/perl5/bin:/usr/local/bin:/usr/bin:/ usr/local/sbin:/usr/sbin:/usr/local/cuda/bin:/act/bin:/home/fmbuga/.lo cal/bin:/home/fmbuga/bin QT_PLUGIN_PATH=/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins REQUESTS_CA_BUNDLE=<not set> SSL_CERT_FILE=<not set> active environment : base active env location : /home/fmbuga/.conda/envs/clair3a shell level : 3 user config file : /home/fmbuga/.condarc populated config files : /home/fmbuga/.condarc conda version : 4.14.0 conda-build version : not installed python version : 3.9.0.final.0 virtual packages : __linux=3.10.0=0 __glibc=2.17=0 __unix=0=0 __archspec=1=x86_64 base environment : /home/fmbuga/.conda/envs/clair3a (writable) conda av data dir : /home/fmbuga/.conda/envs/clair3a/etc/conda conda av metadata url : None channel URLs : https://conda.anaconda.org/conda-forge/linux-64 https://conda.anaconda.org/conda-forge/noarch https://conda.anaconda.org/bioconda/linux-64 https://conda.anaconda.org/bioconda/noarch https://repo.anaconda.com/pkgs/main/linux-64 https://repo.anaconda.com/pkgs/main/noarch https://repo.anaconda.com/pkgs/r/linux-64 https://repo.anaconda.com/pkgs/r/noarch https://conda.anaconda.org/main/linux-64 https://conda.anaconda.org/main/noarch package cache : /home/fmbuga/.conda/envs/clair3a/pkgs /home/fmbuga/.conda/pkgs envs directories : /home/fmbuga/.conda/envs/clair3a/envs /home/fmbuga/.conda/envs platform : linux-64 user-agent : conda/4.14.0 requests/2.28.1 CPython/3.9.0 Linux/3.10.0-1062.18.1.el7.x86_64 centos/7.9.2009 glibc/2.17 UID:GID : 1179:1090 netrc file : None offline mode : False An unexpected error has occurred. Conda has prepared the above report. [- ] process > check_for_alignment - [- ] process > minimap2_ubam - [- ] process > cram_cache - [- ] process > mosdepth - [- ] process > mapula - [- ] process > snp:make_chunks - [- ] process > snp:pileup_variants - [- ] process > snp:aggregate_pileup_variants - [- ] process > snp:select_het_snps - [- ] process > snp:phase_contig - [- ] process > snp:get_qual_filter - [- ] process > snp:create_candidates - [- ] process > snp:evaluate_candidates - [- ] process > snp:aggregate_full_align_va... - [- ] process > snp:merge_pileup_and_full_vars - [- ] process > snp:aggregate_all_variants - [- ] process > snp:readStats - [- ] process > snp:getVersions - [- ] process > snp:getParams - [- ] process > snp:vcfStats - [- ] process > snp:makeReport - [- ] process > output_snp - [- ] process > sv:variantCall:filterBam - [- ] process > sv:variantCall:sniffles2 - [- ] process > sv:variantCall:filterCalls - [- ] process > sv:variantCall:sortVCF - [- ] process > sv:variantCall:indexVCF - [- ] process > sv:runReport:getVersions - [- ] process > sv:runReport:getParams - [- ] process > sv:runReport:report - [- ] process > output_sv - [- ] process > publish_artifact - Error executing process > 'sv:runReport:getParams' Caused by: Failed to create Conda environment command: mamba env create --prefix /home/fmbuga/nanopore/nf/output/workspace/conda/epi2melabs-wf-human-sv-92d947f1f2139701fe2b7c5b2adb0786 --file /home/fmbuga/.nextflow/assets/epi2me-labs/wf-human-variation/environment_sv.yaml status : 1 message: warning libmamba Cannot lock '/home/fmbuga/.conda/envs/clair3a/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/envs/clair3a/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/envs/clair3a/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/envs/clair3a/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/envs/clair3a/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/envs/clair3a/pkgs/cache' Waiting for other mamba process to finish warning libmamba Cannot lock '/home/fmbuga/.conda/envs/clair3a/pkgs/cache/497deca9.json' Waiting for other mamba process to finish error libmamba Error opening for reading "/home/fmbuga/.conda/envs/clair3a/pkgs/zlib-1.2.12-h166bdaf_4/info/index.json": No such file or directory error libmamba Error when extracting package: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<< Traceback (most recent call last): File "/home/fmbuga/.conda/envs/clair3a/lib/python3.9/site-packages/conda/exceptions.py", line 1125, in __call__ return func(*args, **kwargs) File "/home/fmbuga/.conda/envs/clair3a/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call exit_code = getattr(module, func_name)(args, parser) File "/home/fmbuga/.conda/envs/clair3a/lib/python3.9/site-packages/conda/notices/core.py", line 72, in wrapper return_value = func(*args, **kwargs) File "/home/fmbuga/.conda/envs/clair3a/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 156, in execute result[installer_type] = installer.install(prefix, pkg_specs, args, env) File "/home/fmbuga/.conda/envs/clair3a/lib/python3.9/site-packages/mamba/mamba_env.py", line 153, in mamba_install transaction.fetch_extract_packages() RuntimeError: Found incorrect download: zlib. Aborting `$ /home/fmbuga/.conda/envs/clair3a/bin/mamba create --prefix /home/fmbuga/nanopore/nf/output/workspace/conda/epi2melabs-wf-human-sv-92d947f1f2139701fe2b7c5b2adb0786 --file /home/fmbuga/.nextflow/assets/epi2me-labs/wf-human-variation/environment_sv.yaml` environment variables: CIO_TEST=<not set> CONDA_AUTO_UPDATE_CONDA=false CONDA_DEFAULT_ENV=clair3a CONDA_EXE=/home/fmbuga/.conda/envs/clair3a/bin/conda CONDA_PREFIX=/home/fmbuga/.conda/envs/clair3a CONDA_PREFIX_1=/opt/intel/intelpython3 CONDA_PREFIX_2=/home/fmbuga/.conda/envs/gatk4 CONDA_PROMPT_MODIFIER=(clair3a) CONDA_PYTHON_EXE=/home/fmbuga/.conda/envs/clair3a/bin/python CONDA_ROOT=/home/fmbuga/.conda/envs/clair3a CONDA_SHLVL=3 CURL_CA_BUNDLE=<not set> GDL_PATH=+/usr/share/gnudatalanguage JAVA_LD_LIBRARY_PATH=/home/fmbuga/.conda/envs/clair3a/jre/lib/amd64/server MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles:/act/modulefiles PATH=/home/fmbuga/.conda/envs/clair3a/bin:/opt/intel/intelpython3/condabin: /usr/lib64/qt-3.3/bin:/home/fmbuga/perl5/bin:/usr/local/bin:/usr/bin:/ usr/local/sbin:/usr/sbin:/usr/local/cuda/bin:/act/bin:/home/fmbuga/.lo cal/bin:/home/fmbuga/bin QT_PLUGIN_PATH=/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins REQUESTS_CA_BUNDLE=<not set> SSL_CERT_FILE=<not set> active environment : base active env location : /home/fmbuga/.conda/envs/clair3a shell level : 3 user config file : /home/fmbuga/.condarc populated config files : /home/fmbuga/.condarc conda version : 4.14.0 conda-build version : not installed python version : 3.9.0.final.0 virtual packages : __linux=3.10.0=0 __glibc=2.17=0 __unix=0=0 __archspec=1=x86_64 base environment : /home/fmbuga/.conda/envs/clair3a (writable) conda av data dir : /home/fmbuga/.conda/envs/clair3a/etc/conda conda av metadata url : None channel URLs : https://conda.anaconda.org/conda-forge/linux-64 https://conda.anaconda.org/conda-forge/noarch https://conda.anaconda.org/bioconda/linux-64 https://conda.anaconda.org/bioconda/noarch https://repo.anaconda.com/pkgs/main/linux-64 https://repo.anaconda.com/pkgs/main/noarch https://repo.anaconda.com/pkgs/r/linux-64 https://repo.anaconda.com/pkgs/r/noarch https://conda.anaconda.org/main/linux-64 https://conda.anaconda.org/main/noarch package cache : /home/fmbuga/.conda/envs/clair3a/pkgs /home/fmbuga/.conda/pkgs envs directories : /home/fmbuga/.conda/envs/clair3a/envs /home/fmbuga/.conda/envs platform : linux-64 user-agent : conda/4.14.0 requests/2.28.1 CPython/3.9.0 Linux/3.10.0-1062.18.1.el7.x86_64 centos/7.9.2009 glibc/2.17 UID:GID : 1179:1090 netrc file : None offline mode : False An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by SamStudio8** [comment]
I think the locking lines might just be a warning that some of the mamba
processes are waiting for another to finish, the real
trouble seems to be these lines:

> error libmamba Error when extracting package: [json.exception.parse_error.101]
parse error at line 1, column 1: syntax error while parsing value -
unexpected end of input; expected '[', '{', or a literal #

> error libmamba Error opening for reading
"/home/fmbuga/.conda/envs/clair3a/pkgs/zlib-1.2.12-h166bdaf_4/info/index.json":
No such file or directory

I've seen both of these errors occasionally in our CI (and my own usage)
when packages from conda could not be downloaded correctly for whatever
reason. This usually goes away after another attempt, or a few more! The
fragility of the conda package system is one of the reasons we encourage
users to use the Docker and Singularity profiles when possible instead.

Not a very scientific instruction but if you repeat the command to start
the pipeline and install the conda environments again you should have more
luck!

**Comment by felixm3** [comment]
Success!

After the 4th try it was able to get past the conda install issue and then ~20 hours later...

<img width="756" alt="image" src="https://user-images.githubusercontent.com/43228120/194989047-0a639489-7c84-4722-ab69-1f956bc613b9.png">

Thanks! 🥳😀
