### ISSUE TITLE
whatshap 1.7 division by zero bug

### ISSUE THREAD

**Issue by ymcki** [epi2me-labs/wf-human-variation#77]
### Operating System

Ubuntu 22.04

### Workflow Version

v1.7.1

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

None

### What happened?

I was running 1.7.1 with "--snp --sv --str --cnv --phase_methyl --phase_vcf --joint_phasing --depth_intervals" and it worked for all my samples except for one that gave me a division by zero error when executing whatshap stats.

It turns out this is a known bug that happens when there are no heterozygous SNPs on one of the contigs:
https://github.com/whatshap/whatshap/issues/470
It is now fixed in the development version but still in the 2.0 version 
https://whatshap.readthedocs.io/en/latest/changes.html#development-version

Please keep an eye on this bug and update when whatshap 2.1 comes out.

Of course, it would be great if you can fix that for whatshap 2.0 and then make a new wf-human-variation-snp image such that I can simply update the image hash in 1.7.1.

### Relevant log output

```shell
ERROR ~ Error executing process > 'snp:haploblocks_snp (1)'

Caused by:
  Process `snp:haploblocks_snp (1)` terminated with an error exit status (1)

Command executed:

  # Prepare correct input file
  whatshap stats --gtf=ABC.wf_snp.haploblocks.gtf A0002361.wf_snp.vcf.gz

Command exit status:
  1

Command output:
          Longest block:      275    bp
         Shortest block:      275    bp
             Block NG50:        0    bp
  ---------------- Chromosome chrUn_KI270395v1 ----------------
        Variants in VCF:        4
           Heterozygous:        0    (       0    SNVs)
                 Phased:        0    (       0    SNVs)
    Heterozygous phased:        0.0% (       0.0% SNVs)
               Unphased:        0    (not considered below)
             Singletons:        0    (not considered below)
                 Blocks:        0

  Block sizes (no. of variants)
           Sum of sizes:        0    variants
      Median block size:         nan variants
     Average block size:         nan variants
          Largest block:        0    variants
         Smallest block:        0    variants

  Block lengths (basepairs)
         Sum of lengths:        0    bp
    Median block length:         nan bp
   Average block length:         nan bp
          Longest block:        0    bp
         Shortest block:        0    bp
             Block NG50:      nan    bp
  ---------------- Chromosome chrUn_KI270420v1 ----------------
        Variants in VCF:       40
           Heterozygous:       34    (      34    SNVs)
                 Phased:       19    (      19    SNVs)
    Heterozygous phased:       55.9% (      55.9% SNVs)
               Unphased:       15    (not considered below)
             Singletons:        0    (not considered below)
                 Blocks:        1

  Block sizes (no. of variants)
           Sum of sizes:       19    variants
      Median block size:       19.00 variants
     Average block size:       19.00 variants
          Largest block:       19    variants
         Smallest block:       19    variants

  Block lengths (basepairs)
         Sum of lengths:     1201    bp
    Median block length:     1201.00 bp
   Average block length:     1201.00 bp
          Longest block:     1201    bp
         Shortest block:     1201    bp
             Block NG50:     1201    bp
  ---------------- Chromosome chrUn_KI270583v1 ----------------

Command error:
  Block sizes (no. of variants)
           Sum of sizes:        0    variants
      Median block size:         nan variants
     Average block size:         nan variants
          Largest block:        0    variants
         Smallest block:        0    variants

  Block lengths (basepairs)
         Sum of lengths:        0    bp
    Median block length:         nan bp
   Average block length:         nan bp
          Longest block:        0    bp
         Shortest block:        0    bp
             Block NG50:      nan    bp
  ---------------- Chromosome chrUn_KI270420v1 ----------------
        Variants in VCF:       40
           Heterozygous:       34    (      34    SNVs)
                 Phased:       19    (      19    SNVs)
    Heterozygous phased:       55.9% (      55.9% SNVs)
               Unphased:       15    (not considered below)
             Singletons:        0    (not considered below)
                 Blocks:        1

  Block sizes (no. of variants)
           Sum of sizes:       19    variants
      Median block size:       19.00 variants
     Average block size:       19.00 variants
          Largest block:       19    variants
         Smallest block:       19    variants

  Block lengths (basepairs)
         Sum of lengths:     1201    bp
    Median block length:     1201.00 bp
   Average block length:     1201.00 bp
          Longest block:     1201    bp
         Shortest block:     1201    bp
             Block NG50:     1201    bp
  ---------------- Chromosome chrUn_KI270583v1 ----------------
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/bin/whatshap", line 10, in <module>
      sys.exit(main())
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/whatshap/__main__.py", line 64, in main
      module.main(args)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/whatshap/cli/stats.py", line 565, in main
      run_stats(**vars(args))
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/whatshap/cli/stats.py", line 544, in run_stats
      detailed_stats = stats.get_detailed_stats(chr_lengths)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/whatshap/cli/stats.py", line 316, in get_detailed_stats
      phased_snvs_fraction=phased_snvs / self.heterozygous_snvs,
  ZeroDivisionError: division by zero
```

**Comment by RenzoTale88** [comment]
@ymcki `wf-human-variation` v1.7.2 now has `whatshap` v2.0 with the patch applied. Could you try and see if this works?

**Comment by ymcki** [comment]
Wow. Didn't expect a quick fix. I am running it on the problematic sample now. Will report it back when it is done.

**Comment by ymcki** [comment]
I can confirm that it is working. Thanks for the fix.
