### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rob234king** [epi2me-labs/wf-human-variation#8]
### What happened?

A bug happened!

nextflow run epi2me-labs/wf-human-variation --help
N E X T F L O W  ~  version 22.04.3
Pulling epi2me-labs/wf-human-variation ...
WARN: Cannot read project manifest -- Cause: Not authorized -- Check that the GitHub user name and password provided are correct
Not authorized -- Check that the GitHub user name and password provided are correct

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Version

0.2.2

### Relevant log output

```shell
Sep-29 10:35:33.843 [main] DEBUG nextflow.cli.Launcher - $> nextflow run epi2me-labs/wf-human-variation --help
Sep-29 10:35:33.910 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 22.04.3
Sep-29 10:35:34.583 [main] INFO  nextflow.cli.CmdRun - Pulling epi2me-labs/wf-human-variation ...
Sep-29 10:35:34.585 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials rob234king:****************************************] -> https://api.github.com/repos/epi2me-labs/wf-human-variation/contents/nextflow.config
Sep-29 10:35:35.424 [main] DEBUG nextflow.scm.RepositoryProvider - Response status: 401 -- {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
Sep-29 10:35:35.440 [main] WARN  nextflow.scm.AssetManager - Cannot read project manifest -- Cause: Not authorized -- Check that the GitHub user name and password provided are correct
nextflow.exception.AbortOperationException: Not authorized -- Check that the GitHub user name and password provided are correct
	at nextflow.scm.RepositoryProvider.checkResponse(RepositoryProvider.groovy:174)
	at nextflow.scm.RepositoryProvider.invoke(RepositoryProvider.groovy:138)
	at nextflow.scm.RepositoryProvider.memoizedMethodPriv$invokeAndParseResponseString(RepositoryProvider.groovy:220)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
	at nextflow.scm.RepositoryProvider$_closure2.doCall(RepositoryProvider.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:113)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
	at groovy.lang.Closure.call(Closure.java:428)
	at nextflow.scm.RepositoryProvider.invokeAndParseResponse(RepositoryProvider.groovy)
	at nextflow.scm.GithubRepositoryProvider.readBytes(GithubRepositoryProvider.groovy:100)
	at nextflow.scm.RepositoryProvider.readText(RepositoryProvider.groovy:234)
	at nextflow.scm.AssetManager.getManifest0(AssetManager.groovy:457)
	at nextflow.scm.AssetManager.memoizedMethodPriv$getManifest(AssetManager.groovy:450)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
	at nextflow.scm.AssetManager$_closure2.doCall(AssetManager.groovy)
	at nextflow.scm.AssetManager$_closure2.doCall(AssetManager.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:113)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
	at groovy.lang.Closure.call(Closure.java:406)
	at nextflow.scm.AssetManager.getManifest(AssetManager.groovy)
	at nextflow.scm.AssetManager.getMainScriptName(AssetManager.groovy:433)
	at nextflow.scm.AssetManager.checkValidRemoteRepo(AssetManager.groovy:391)
	at nextflow.scm.AssetManager.download(AssetManager.groovy:600)
	at nextflow.scm.AssetManager.download(AssetManager.groovy)
	at nextflow.cli.CmdRun.getScriptFile0(CmdRun.groovy:477)
	at nextflow.cli.CmdRun.getScriptFile(CmdRun.groovy:410)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:287)
	at nextflow.cli.Launcher.run(Launcher.groovy:480)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)
Sep-29 10:35:35.446 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials rob234king:****************************************] -> https://api.github.com/repos/epi2me-labs/wf-human-variation/contents/main.nf
Sep-29 10:35:35.592 [main] DEBUG nextflow.scm.RepositoryProvider - Response status: 401 -- {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
Sep-29 10:35:35.593 [main] DEBUG nextflow.cli.Launcher - Operation aborted
nextflow.exception.AbortOperationException: Not authorized -- Check that the GitHub user name and password provided are correct
	at nextflow.scm.RepositoryProvider.checkResponse(RepositoryProvider.groovy:174)
	at nextflow.scm.RepositoryProvider.invoke(RepositoryProvider.groovy:138)
	at nextflow.scm.RepositoryProvider.memoizedMethodPriv$invokeAndParseResponseString(RepositoryProvider.groovy:220)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
	at nextflow.scm.RepositoryProvider$_closure2.doCall(RepositoryProvider.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:113)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
	at groovy.lang.Closure.call(Closure.java:428)
	at nextflow.scm.RepositoryProvider.invokeAndParseResponse(RepositoryProvider.groovy)
	at nextflow.scm.GithubRepositoryProvider.readBytes(GithubRepositoryProvider.groovy:100)
	at nextflow.scm.RepositoryProvider.validateFor(RepositoryProvider.groovy:248)
	at nextflow.scm.AssetManager.checkValidRemoteRepo(AssetManager.groovy:392)
	at nextflow.scm.AssetManager.download(AssetManager.groovy:600)
	at nextflow.scm.AssetManager.download(AssetManager.groovy)
	at nextflow.cli.CmdRun.getScriptFile0(CmdRun.groovy:477)
	at nextflow.cli.CmdRun.getScriptFile(CmdRun.groovy:410)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:287)
	at nextflow.cli.Launcher.run(Launcher.groovy:480)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)
```

**Comment by SamStudio8** [comment]
Hi @rob234king. From your log I can see you've defined an [SCM configuration for Github](https://www.nextflow.io/docs/latest/sharing.html#github-credentials):

> `nextflow.scm.RepositoryProvider - Request [credentials rob234king:*]`

Either the personal access token (PAT) you have used in the SCM configuration has expired, or the PAT you are using does not have the `repo:public_repo` scope to pull from public repos.

**Comment by rob234king** [comment]
ah yea likely token has expired, thanks
